### ISSUE TITLE
Зачем C77_Mutual_Investment_Fund_Name_Entity, есть C38_Name_Entity

### ISSUE THREAD

**Issue by KMax** [DataFabricRus/ontology-fts#14]
Зачем нужен отдельный класс (`C77_Mutual_Investment_Fund_Name_Entity`) для имени ПИФа? Есть ведь уже `C38_Name_Entity`.

**Comment by ehlyzov** [comment]
Смотрим если есть дополнительная семантика и если нет, то удаляем
