### ISSUE TITLE
В пример нет связи между C52_Job_Entity и ФЗ

### ISSUE THREAD

**Issue by KMax** [DataFabricRus/ontology-fts#15]
В [пример](https://github.com/DataFabricRus/ontology-fts/blob/master/fts-ex-le.ttl) нет связи между экземпляром `C52_Job_Entity` и экземпляром `C63_Person_Entity` или `C51_Person_Acting_Without_Power_Of_Auttorney_Entity`

**Comment by yuricus** [comment]
Когда исследуешь связь руководителя с компанией, необходимо знать и факт руководства, и должность человека. Иначе это очень неудобно собирать по графу. В случае с property graph мне было бы удобно иметь свойство должности на связи человек-компания

**Comment by KMax** [comment]
Нашел, связь идет через свойство `p121_holds_position`.
