### ISSUE TITLE
Ресурс "ЮЛ" == Ресурс "Запись о ОГРН и т.д."

### ISSUE THREAD

**Issue by KMax** [DataFabricRus/ontology-fts#16]
В онтологии подразумевается, что запись о ОГРН и т.д. юридического лица - это и есть само ЮЛ. Соответственно, если такая запись меняется, то и ЮЛ другое.

Предложение: разделить ресурс "ЮЛ" и ресурс "запись о ОГРН и т.д.", иначе неправильно говорить, что `fts:C9_LegalEntity` - подкласс класса `org:Organisation`.

**Comment by ehlyzov** [comment]
А разве не `fts:C4_Legal_Entity_Details` является классом выписки ЕГРЮЛ? А `fts:C9_Legal_Entity` – это чисто подкласс `org:Organisation`

**Comment by KMax** [comment]
> А разве не fts:C4_Legal_Entity_Details является классом выписки ЕГРЮЛ?

Да, так и есть.

**Comment by ehlyzov** [comment]
Тогда я не совсем понял о чем тикет, можешь детализировать? Получается, что у нас отдельно есть класс выписки и отдельно класс ЮЛ, при этом экземпляр выписки содержит формальную информацию о компании. Разве это не означает что соответствующие ресурсы разделены?
