### ISSUE TITLE
Заменить *_tax_number на gr:taxID

### ISSUE THREAD

**Issue by KMax** [DataFabricRus/ontology-fts#20]
У нас есть `p35_le_individual_tax_number`, `p75_ie_individual_tax_number` предлагаю заменить (генерилизовать) на [gr:taxID](http://www.heppnetz.de/ontologies/goodrelations/v1.html#taxID).

**Comment by ehlyzov** [comment]
Предлагаю рассмотреть в качестве альтернативы gr:taxID использовать rov:registration . Основываясь на том, что rov для нас существенно ближе по смыслу и задумке чем gr.

**Comment by yuricus** [comment]
Может быть, если использовать какую онтологию, то в большем объеме? а то только одно свойство одиноко выглядит

**Comment by KMax** [comment]
> Может быть, если использовать какую онтологию, то в большем объеме? а то только одно свойство одиноко выглядит

Сложно какую-то онтологию в чистую использовать. Например, у `gr` есть `gr:BusinessEntity`, который в нашем случае был бы суперкласс от ЮЛ и ИП, но в прямую его юзать бесполезно, я думаю, только мапится на него.

Хотя, да я поддерживаю желание как можно больше переиспользовать.

**Comment by KMax** [comment]
> Предлагаю рассмотреть в качестве альтернативы gr:taxID использовать rov:registration .

Разве он для ИНН подойдет?

> The vocabulary sets no restriction on the type of legal identifier. In many countries, the business register's identifier is the relevant data point. The tax number often fulfils this function in Spain and elsewhere. [источник](https://www.w3.org/TR/vocab-regorg/#ref_rov_registration)

Скорее для ОГРН подойдет, я думаю.

**Comment by ehlyzov** [comment]
В моем понимании, rov:registration отмечает факт регистрации компании в неком регистрирующем органе. 

```xml
<rov:registration>
<adms:Identifier rdf:about="http://example.com/Reg415622333">
<skos:notation>0415.622.333</skos:notation>
<adms:schemeAgency>Belgian Base Register for Companies</adms:schemeAgency>
</adms:Identifier>
</rov:registration>
```

пример отсюда: https://joinup.ec.europa.eu/sites/default/files/2c/5b/ae/Case%20Study%20-%20How_to_describe_Organizations_in_RDF_Core_Business_Vocabulary.pdf

Соответственно он должен подойти и для ОГРН и для ИНН . А почему ты выбрал goodrelations? Я в работах больше натыкался на использование rov.

**Comment by KMax** [comment]
Более неактуальна, так как перешли на FIBO.
